const { body } = require("express-validator");

const shopSchema = [
  body("orderAccepting")
    .exists()
    .withMessage("Order accepting is required")
    .trim()
    .not()
    .isEmpty()
    .withMessage("Order accepting is required")
    .isBoolean()
    .withMessage("Order accepting must be a boolean value"),
  body("bwprice")
    .exists()
    .withMessage("Black and white price is required")
    .trim()
    .not()
    .isEmpty()
    .withMessage("Black and white price is required")
    .isNumeric()
    .withMessage("Black and white price must be a number"),
  body("colorprice")
    .exists()
    .withMessage("Color price is required")
    .trim()
    .not()
    .isEmpty()
    .withMessage("Color price is required")
    .isNumeric()
    .withMessage("Color price must be a number"),
  body("coverprice")
    .exists()
    .withMessage("Cover price is required")
    .trim()
    .not()
    .isEmpty()
    .withMessage("Cover price is required")
    .isNumeric()
    .withMessage("Cover price must be a number"),
  body("bindingprice")
    .exists()
    .withMessage("Binding price is required")
    .trim()
    .not()
    .isEmpty()
    .withMessage("Binding price is required")
    .isNumeric()
    .withMessage("Binding price must be a number"),
  body("deliveryprice")
    .exists()
    .withMessage("Delivery price is required")
    .trim()
    .not()
    .isEmpty()
    .withMessage("Delivery price is required")
    .isNumeric()
    .withMessage("Delivery price must be a number"),
  body("spiralprice")
    .exists()
    .withMessage("Spiral price is required")
    .trim()
    .not()
    .isEmpty()
    .withMessage("Spiral price is required")
    .isNumeric()
    .withMessage("Spiral price must be a number"),
  // body('owner')
  // .exists()
  // .withMessage('Owner is required')
  // .trim()
  // .not()
  // .isEmpty()
  // .withMessage('Owner is required')
  // .isMongoId()
  // .withMessage('Owner must be a valid mongo id')
];
